### ISSUE TITLE
[unified2orchestra] override metadata from unified repository source

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#110]
The immediate problem is that the unified repository schema does not support "FIXLatest" as a version, and we don't wish to change that schema now. More generally, Orchestra supports richer metadata using Dublin Core Terms, but unified does not have sources for it.

Therefore, it would be useful to add an input to unified2orchestra to supply any desired metadata. It could come from command line arguments or a separate file.

**Comment by kleihan** [comment]
Understand, here is the XSD snippet containing versions in the unified schema:

```
<xs:simpleType name="Version_t">
  <xs:restriction base="xs:string">
    <xs:pattern value="(FIX.2.7)|(FIX.3.0)|(FIX\.4\.[0-4])|(FIX\.5\.0(SP\d{1,2})?(_EP((9[8-9])|([1-9][0-9][0-9])))?)|(FIXT.1.1)"/>		
  </xs:restriction>
</xs:simpleType>
```

Agree to a leave the unified schema unchanged. The bigger question is whether we can change the semantic of version and EP identification in Orchestra. Otherwise, FIX 5.0 SP2 will remain the base version for all EPs in the future. Current logic is that the version number represents the FIX version ***prior*** to the referenced EP, e.g. `added="FIX.5.0SP1" addedEP="96"` means "FIX 5.0 SP1 enhanced with EP96 after publication of SP1, to be rolled into the next FIX version, i.e. FIX 5.0 SP2".

I would like to change that semantic for Orchestra to mean that the EP is part of the version, i.e. the example would need to be changed to `added="FIX.5.0SP2" addedEP="96"`, i.e. "EP96 as part of FIX 5.0 SP2". We can then identify everything with "FIX.Latest_EPnnn" to mean "EPnnn as part of FIX Latest".

An alternative may be to identify an EP above EP98 as the starting point for FIX Latest, e.g. EP260 (EP that introduced FIX Latest as new value for ApplVerID(1128)). Then we would only change the reference as of EP260 to change from "FIX.5.0SP2" to "FIX.Latest", e.g. "FIX.Latest_EP264". That may be a cleaner solution and equally meets the objective of moving away from FIX versioning.

**Comment by donmendelson** [comment]
Here is the equivalent version pattern in Orchestra schema. It is a superset of the unified type. In addition to the FIXx.x tags, it also supports dotted decimal version numbers and 8 digit date without the "FIX" literal.

```
<xs:simpleType name="Version_t">
		<xs:restriction base="xs:string">
			<xs:annotation>
				<xs:documentation>Enumerated FIX versions or major.minor or date as
					yyyymmdd of any protocol
				</xs:documentation>
			</xs:annotation>
			<xs:pattern value="(FIX.2.7)|(FIX.3.0)|(FIX\.4\.[0-4])|(FIX\.5\.0(SP\d{1,2})?(_EP((9[8-9])|([1-9][0-9][0-9])))?)|(FIXT.1.1)|([0-9]+)\.([0-9]+)|(\d{8})"/>
		</xs:restriction>
	</xs:simpleType>
```

If this is insufficient, we can simply make version a free-format string of a firm's own choosing.

**Comment by kleihan** [comment]
Adding "FIX.Latest" or simply "FIXLatest" as an additional option should suffice. If the dots are only to separate major/minor version numbers then we do not need one. Applying the change only to EP260 and above seems least invasive and reasonable to me.

**Comment by chrjohn** [comment]
I have a question regarding the notation. What is the difference between "FIX.Latest" and "FIXLatest", especially *why is there* a notation with and without dot? Example from fiximate for FIX50SP2:
![image](https://user-images.githubusercontent.com/6644028/102560194-f2284500-40d1-11eb-8b63-4224d59fd696.png)

Just as an explanation why I am asking: only having "FIXLatest" might require more special handling in existing code because most places I've seen use logic which concatenates "FIX.major.minor" which would lead to "FIX.FIXLatest" (assuming that FIXLatest is a major version and there will be no additional attribute introduced).

**Comment by kleihan** [comment]
@chrjohn thanks for that feedback, agree to avoid "FIX.FIXLatest". Would use of "Latest" as major version without any minor version solve the issue?

The values and symbolic names for ApplVerID(1128) in FIXimate have always been without dots. I am not aware of any difference between the two syntaxes and we should try to minimize disruption whilst making sure that FIX Latest is not only visible on slides but also in the repository. "Latest" is obviously a string and not an integer, that would be different from previous versions.

**Comment by chrjohn** [comment]
> Would use of "Latest" as major version without any minor version solve the issue?

Yes, I think it would be consistent with the former versioning scheme.

**Comment by donmendelson** [comment]
Pattern not working correctly to support version "FIX.Latest_EP264"
