### ISSUE TITLE
Restricted characters in fix:code

### ISSUE THREAD

**Issue by YuvalCohen** [FIXTradingCommunity/fix-orchestra#119]
YC: The content of this issue has changed (previous content is not relevant)

RepositoryValidator forbids white spaces in fix:code

**Comment by YuvalCohen** [comment]
Note that RepositoryValidator  forbids white spaces. 

```
static final Predicate<String> isValidString =
t -> t.length() > 0 && t.chars().noneMatch(Character::isWhitespace);
```

We think that this validation is redundant as it happens by the schema.

**Comment by donmendelson** [comment]
@YuvalCohen the rule that you cite is in new class FixRepositoryValidator that is designed to enforce FIX rules. The class BasicRepositoryValidator allows any string. You can use it directly or subclass it to specify your own validation rules.

My recommendation is to change the Orchestra schema (will be version 1.1) to be more permissive and defer style rules for specific protocols to a purpose-build validator. Aside from names, I expect style rules for versioning might be different as well.

**Comment by donmendelson** [comment]
White space could be enforced by the XML schema if we change the datatype of names to "token" rather than string.

"The token data type is also derived from the String data type."
"The token data type also contains characters, but the XML processor will remove line feeds, carriage returns, tabs, leading and trailing spaces, and multiple spaces."

This would still allow internal spaces for protocols that allow it (includes DSB). FixRepositoryValidator could warn on internal spaces.

**Comment by kleihan** [comment]
Implemented for RC1
