### ISSUE TITLE
Rule language label

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#32]
As part of Orchestra, we have defined a Domain Specific Language (DSL) called Score for conditional expressions. However, some users may wish to use a different programming language, e.g. Groovy or Typescript. We can  add an attribute to rule elements to specify the programming language. It can default to Score so we don't need to label every rule.

**Comment by donmendelson** [comment]
Question: is it sufficient to have one expression language label for a whole Orchestra file, or might users mix languages in a file so you would need a language label on each rule?

**Comment by kleihan** [comment]
I would start with a file level attribute, if at all. Can you automatically translate between different DSLs? Otherwise, it will not be enough to bilaterally agree on using Orchestra, one has to be using the same DSL. I would see this feature as something "user-defined", i.e. the standard foresees Score but parties can agree on using something else and we define an explicit label to support this.
