### ISSUE TITLE
Question: Orchestra Tooling update

### ISSUE THREAD

**Issue by nngakosso** [FIXTradingCommunity/fix-orchestra#90]
Hello, I would like to get a quick update if possible about Orchestra tools. Are ORCHID, log2Orchestra and Orchestra translator running? What about Orchestra2Html, Orchestra 2 quickfix? What has been tested so far?

Thank you,

Regards,

Ndakey

**Comment by donmendelson** [comment]
@nngakosso this project is public. Its utilities and their enhancements will be available to all Orchestra users as soon as they are pushed. You will find some demonstration code to work with QuickFIX here, both for message definitions and generating session configurations.

The other tools that you mentioned will be available only to members of FIX Trading Community. Development status will be reported to the Orchestra working group rather than through GitHub. Program access will be granted through that group and the program office.
